version: '3.9'

services:
  db:
    image: 'postgres'
    network_mode: bridge
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_DB: northwind_db
    expose:
      - 5438
    ports: 
      - 5438:5432
    volumes:
      - data:/var/lib/postgresql/data
      - ./_scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./api-gateway
      dockerfile: ./Dockerfile
    network_mode: bridge
    container_name: api
    environment:
      DRIZZLE_HOST: drizzle:8001
      TYPEORM_HOST: typeorm:8002
      KNEX_HOST: knex:8003
      KYSELY_HOST: kysely:8004
      PRISMA_HOST: prisma:8005
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - drizzle
      - typeorm
      - knex
      - kysely
      - prisma
    links:
      - drizzle
      - typeorm
      - knex
      - kysely
      - prisma

  drizzle:
    build:
      context: ./drizzle-orm
      dockerfile: ./Dockerfile
    network_mode: bridge
    container_name: drizzle
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: adminadmin
      DB_NAME: northwind_db
    expose:
      - 8001
    ports:
      - 8001:8001
    depends_on:
      - db
    links:
      - db

  typeorm:
    build:
      context: ./typeorm
      dockerfile: ./Dockerfile
    network_mode: bridge
    container_name: typeorm
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: adminadmin
      DB_NAME: northwind_db
    expose:
      - 8002
    ports:
      - 8002:8002
    depends_on:
      - db
    links:
      - db

  knex:
    build:
      context: ./knex-orm
      dockerfile: ./Dockerfile
    network_mode: bridge
    container_name: knex
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: adminadmin
      DB_NAME: northwind_db
    expose:
      - 8003
    ports:
      - 8003:8003
    depends_on:
      - db
    links:
      - db
  
  kysely:
    build:
      context: ./kysely-orm
      dockerfile: ./Dockerfile
    network_mode: bridge
    container_name: kysely
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: adminadmin
      DB_NAME: northwind_db
    expose:
      - 8004
    ports:
      - 8004:8004
    depends_on:
      - db
    links:
      - db

  prisma:
    build:
      context: ./prisma-orm
      dockerfile: ./Dockerfile
    network_mode: bridge
    container_name: prisma
    environment:
      DATABASE_URL: postgresql://postgres:adminadmin@db:5432/northwind_db
    expose:
      - 8005
    ports:
      - 8005:8005
    depends_on:
      - db
    links:
      - db

volumes:
  data:
